### ISSUE TITLE
setKeyColor don't work on razer deathstalker ..

### ISSUE THREAD

**Issue by Jerem584** [jglrxavpok/JChroma#1]
Hey!

When i'm trying to make a simple code; he dont work ... 

For example:

        CustomKeyboardEffect effect = new CustomKeyboardEffect();
        ColorRef red = new ColorRef(255, 0, 0);
        effect.setKeyColor(KeyboardKeys.RZKEY_V, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_F, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_G, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_E, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_R, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_T, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_Y, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_4, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_6, red);

        chroma.createKeyboardEffect(effect);

this won't work ... no exception; other effect work

**Comment by jglrxavpok** [comment]
Hello!

This looks like it is from the 'heart' test in TestEffects, does the test 'custom' work ?
Also, are you ensuring the program does not immediatly stop after 'createKeyboardEffect' ?

**Comment by Jerem584** [comment]
The custom effect don't work, but other works... Wave Work. heart Don't work.

**Comment by Jerem584** [comment]
With this simple code

		JChroma chroma = JChroma.getInstance();
		chroma.init();
		//chroma.createKeyboardEffect(new StaticKeyboardEffect(ColorRef.fromRGB(Color.RED.getRGB())));
		while(true)
		{
        CustomKeyboardEffect effect = new CustomKeyboardEffect();
        ColorRef red = new ColorRef(255, 0, 0);
        effect.setKeyColor(KeyboardKeys.RZKEY_V, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_F, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_G, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_E, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_R, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_T, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_Y, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_4, red);
        effect.setKeyColor(KeyboardKeys.RZKEY_6, red);


        chroma.createKeyboardEffect(effect);
        System.out.println("Working");
	}


The console say Working working ... But my keyboard don't have the custom color all leds are OFF

**Comment by Jerem584** [comment]
BUT ! 

the method setColor(row, collumn, color) Work !

**Comment by jglrxavpok** [comment]
I'm afraid this problem comes from the DeathStalker rather than the library, as it appears the keyboard cannot change the color of a single key at a time

http://developer.razerzone.com/works-with-chroma/razer-chroma-led-profiles/
https://insider.razerzone.com/index.php?threads/custom-effects-on-the-deathstalker-chroma.10697/#post-185760
https://insider.razerzone.com/index.php?threads/sdk-with-deathstalker.22312/#post-340774

**Comment by Jerem584** [comment]
oh god! why ? Like seriously, they normal keyboard is good ! but death stalker is just a shitty one! No chroma profiles (except 2-3), can't change color per key... :(

**Comment by Jerem584** [comment]
Okay so

With the first link (Led profiles) we can see the Generic Super Keyboard

who support one key color changing and deathstalker chorma can we do something with ?

**Comment by jglrxavpok** [comment]
I do not see the DeathStalker in the Generic Super Keyboard supported keyboards and I'm afraid there is nothing that can be done

**Comment by Jerem584** [comment]
Oh fuck :( , thanks for your help... Have a nice day 👍
