### ISSUE TITLE
What's the depencency repo?

### ISSUE THREAD

**Issue by TheFlash787** [jglrxavpok/JChroma#3]
Hey? How can we import this?

`compile 'com.github.jglrxavpok:jchroma:master'` doesn't appear to work.

**Comment by jglrxavpok** [comment]
Sadly there is no Maven repository hosting this lib
I've added a License file if you want to redistribute the code

**Comment by TheFlash787** [comment]
How do we include it into our project then?

**Comment by jglrxavpok** [comment]
If you clone the repository you can either:
- Include the sources directly in your project
- Build an artifact with Gradle
- Use the repository as a git submodule and a Gradle subproject
